name: 构建efb-v2 Docker镜像

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "efb-v2/Dockerfile"
  repository_dispatch:
    types: efb-v2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date tag
        id: Tags
        run: echo "::set-output name=dtTag::$(date +"%Y%m%d%H")"
        
      - name: 构建并推送到Dockerhub和ghcr.io镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./efb-v2/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            akyakya/efb-v2:latest
            akyakya/efb-v2:${{ steps.Tags.outputs.dtTag }}
